[tool.kedro]
package_name = "citec_platform"
project_name = "citec_platform"
project_version = "0.0.1"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88